# Generated by Django 4.1.5 on 2023-02-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской пол'), ('female', 'Женский пол')], default='male', max_length=20, verbose_name='Пол пользователя'),
        ),
    ]
