# Generated by Django 4.1.5 on 2023-02-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0003_profile_agreement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профайл', 'verbose_name_plural': 'Профайлы'},
        ),
    ]
